let questions = [
    {type: "Si", question: `Est-ce que vous avez besoin de connaître tous les paramètres et détails concrets d'une situation avant de vous lancer ?`},
    {type: "Si", question: `Lorsque vous expliquez quelque chose, est-ce que vous citez spontanément des chiffres, des dates ou des faits précis pour étayer vos propos ?`},
    {type: "Si", question: `Est-ce que le fait de suivre une procédure établie ou un mode d'emploi détaillé vous rassure et vous semble la meilleure façon de faire ?`},
    {type: "Si", question: `Pour vous, une idée est-elle "solide" seulement si elle s'appuie sur des données observables et des preuves concrètes ?`},
    {type: "Si", question: `Est-ce que vous remarquez et mémorisez facilement les petits détails que les autres pourraient négliger (comme un changement dans une pièce, une coquille dans un texte) ?`},
    {type: "Si", question: `Lorsque vous apprenez, est-ce que vous retenez mieux l'information en la classant dans des catégories bien définies et selon des règles claires ?`},
    {type: "Si", question: `Est-ce que vous accordez une grande importance à l'exactitude des mots et à la précision des définitions dans une discussion ?`},
    {type: "Si", question: `Pour évaluer la fiabilité d'une personne, est-ce que vous observez sa constance dans les faits et son respect des engagements pris ?`},
    {type: "Si", question: `Est-ce que vous préférez les consignes et les objectifs clairement énoncés, sans place pour l'ambiguïté ?`},
    {type: "Si", question: `Est-ce que vous avez l'impression que le monde est plus compréhensible lorsqu'on le décompose en éléments simples et vérifiables ?`},

    {type: "Se", question: `Est-ce que vous comprenez et mémorisez mieux les choses en les faisant ou en les expérimentant directement, plutôt qu'en les étudiant de manière théorique ?`},
    {type: "Se", question: `Lorsque vous êtes inactif pendant un certain temps, est-ce que vous ressentez un besoin presque physique de vous lancer dans une action, même simple ?`},
    {type: "Se", question: `Est-ce que votre humeur est souvent influencée par le "rythme" de votre journée (périodes calmes vs périodes d'activité intense) ?`},
    {type: "Se", question: `Pour vous, une invitation a une activité est elle satisfaisante si une action concrète, pas forcément prévue, est réalisée?`},
    {type: "Se", question: `êtes vous concentrer sur l’instant présent plutot que sur le futur ou sur le passé`},
    {type: "Se", question: `Lorsque vous décrivez une expérience, est-ce que vous avez tendance à raconter ce qui s'est passé comme une séquence d'événements et d'actions ?`},
    {type: "Se", question: `Est-ce que vous êtes particulièrement attentif aux feedbacks immédiats de votre environnement (comme un score dans un jeu, la réaction physique d'une personne) ?`},
    {type: "Se", question: `Est-ce que vous préférez les loisirs qui impliquent une participation active (sport, jeux vidéo, bricolage) à ceux qui sont purement contemplatifs ?`},
    {type: "Se", question: `Pour vous, le temps est-il souvent perçu comme une série d' "occasions à saisir" dans l'instant présent ?`},
    {type: "Se", question: `Est-ce que vous avez le sentiment de mieux connaître les gens après avoir partagé une activité avec eux, plutôt qu'après une longue discussion ?`},

    {type: "Ne", question: `Est-ce que votre esprit fonctionne naturellement par associations d'idées, une pensée en amenant une autre de manière parfois imprévisible ?`},
    {type: "Ne", question: `Lorsque vous apprenez un nouveau concept, est-ce que vous passez immédiatement en revue tout ce que vous savez déjà pour trouver des points de connexion ?`},
    {type: "Ne", question: `Est-ce que vous avez souvent l'impression de voir des motifs, des parallèles ou des structures similaires dans des domaines pourtant très différents ?`},
    {type: "Ne", question: `Pour vous, la compréhension d'un sujet est-elle complète seulement lorsque vous avez saisi comment il s'insère dans un système plus vaste ?`},
    {type: "Ne", question: `Est-ce que vous utilisez fréquemment des métaphores ou des analogies pour expliquer votre pensée, car elles révèlent des liens cachés ?`},
    {type: "Ne", question: `Lors d'une conversation, est-ce que vous sautez facilement d'un sujet à l'autre parce que vous percevez le lien qui les unit, même si ce n'est pas évident pour les autres ?`},
    {type: "Ne", question: `Est-ce que vous aimez les cartes mentales, les schémas conceptuels ou tout outil qui permet de visualiser les relations entre les idées ?`},
    {type: "Ne", question: `Trouvez-vous que la beauté d'une idée réside souvent dans son élégance et sa capacité à relier harmonieusement plusieurs concepts ?`},
    {type: "Ne", question: `Est-ce qu'un détail anodin peut déclencher en vous une cascade de réflexions qui vous mènent à un concept très éloigné du point de départ ?`},
    {type: "Ne", question: `Avez-vous le sentiment que la connaissance n'est pas une collection de faits, mais une toile infinie de connexions à explorer ?`},

    {type: "Ni", question: `Est-ce que vous passez beaucoup de temps à réfléchir, à affiner et à parfaire votre vision personnelle du monde pour qu'elle soit la plus cohérente possible ?`},
    {type: "Ni", question: `Lorsque vous rencontrez une nouvelle information, est-ce que vous la "testez" mentalement pour voir si elle s'intègre harmonieusement dans votre système de pensée ?`},
    {type: "Ni", question: `Est-ce que vos décisions importantes sont principalement guidées par la nécessité de rester fidèle à votre vision du monde ?`},
    {type: "Ni", question: `Pour vous, un concept abstrait (comme la justice ou la liberté) a-t-il une "forme" ou une "texture" presque tangible dans votre esprit ?`},
    {type: "Ni", question: `Est-ce que vous avez développé un vocabulaire ou un système de symboles personnel pour décrire des concepts qui vous sont propres ?`},
    {type: "Ni", question: `Lorsque votre vision du monde évolue sur un point, est-ce que cela entraîne souvent une restructuration en cascade de nombreuses autres idées connexes ?`},
    {type: "Ni", question: `Est-ce que vous cherchez constamment la signification ultime derrière les événements et les idées pour en comprendre le concept ?`},
    {type: "Ni", question: `Avez-vous l'impression que votre monde intérieur est un espace riche et organisé, parfois plus réel ou significatif pour vous que le monde extérieur ?`},
    {type: "Ni", question: `Est-ce que vous êtes plus intéressé par la cohérence interne d'une théorie que par son application pratique immédiate ?`},
    {type: "Ni", question: `Est-ce que vous considérez votre vie comme un projet visant à aligner vos actions et vos expériences avec la représentation idéale que vous portez en vous ?`},
    
    {type: "Te", question: "Vous sentez-vous motivé à organiser les choses pour qu'elles soient plus efficaces et productives ?"},
    {type: "Te", question: "Aimez-vous prendre des décisions rapidement en vous basant sur des faits objectifs ?"},
    {type: "Te", question: "Vous trouvez-vous souvent à vouloir structurer et planifier les étapes nécessaires pour atteindre un objectif ?"},
    {type: "Te", question: "Aimez-vous donner des instructions ou conseils pour aider les autres à être plus efficaces ?"},
    {type: "Te", question: "Trouvez-vous que vous prenez facilement les commandes dans les situations qui nécessitent une organisation ?"},
    {type: "Te", question: "Appréciez-vous fixer des objectifs clairs et mesurer vos progrès de manière tangible ?"},
    {type: "Te", question: "Aimez-vous résoudre les problèmes en vous basant sur des données factuelles et objectives ?"},
    {type: "Ti", question: "Avez-vous une tendance à analyser les situations en profondeur pour en comprendre les mécanismes sous-jacents ?"},
    {type: "Ti", question: "Vous appuyez-vous sur des principes logiques internes pour prendre des décisions, même si elles ne sont pas populaires ?"},
    {type: "Ti", question: "Avez-vous un fort besoin de cohérence et de clarté dans vos idées et croyances ?"},
    {type: "Ti", question: "Aimez-vous décomposer des problèmes complexes en éléments plus simples et compréhensibles ?"},
    {type: "Ti", question: "Ressentez-vous une satisfaction personnelle lorsque vous trouvez des solutions logiques et bien raisonnées ?"},
    {type: "Ti", question: "Vous sentez-vous souvent concentré sur le \"pourquoi\" des choses, en cherchant à comprendre leur fonctionnement ?"},
    {type: "Ti", question: "Avez-vous une forte préférence pour des décisions qui s'accordent avec vos propres modèles de pensée logique ?"},
    {type: "Fe", question: "Aimez-vous vous assurer que les autres se sentent bien et sont émotionnellement à l'aise ?"},
    {type: "Fe", question: "Trouvez-vous important de maintenir l'harmonie et d'éviter les conflits au sein de votre entourage ?"},
    {type: "Fe", question: "Vous retrouvez-vous souvent à prendre des décisions basées sur les besoins et les désirs des autres ?"},
    {type: "Fe", question: "Avez-vous tendance à exprimer ouvertement vos émotions et à vous soucier des réactions des autres ?"},
    {type: "Fe", question: "Vous arrive-t-il souvent d'agir pour soutenir ou aider les autres dans leurs difficultés ?"},
    {type: "Fe", question: "Aimez-vous construire des relations chaleureuses et sincères ?"},
    {type: "Fe", question: "Prenez-vous du plaisir à rassemblé les gens et favorisé l'harmonie ?"},
    {type: "Fi", question: "Prenez-vous souvent des décisions en fonction de vos valeurs personnelles profondes ?"},
    {type: "Fi", question: "Vous arrive-t-il de ressentir fortement ce qui est juste ou injuste en fonction de vos propres standards ?"},
    {type: "Fi", question: "Trouvez-vous important de rester fidèle à vous-même, même si cela entre en conflit avec l'avis des autres ?"},
    {type: "Fi", question: "Vous appuyez-vous souvent sur vos convictions personnelles pour évaluer une situation ?"},
    {type: "Fi", question: "Avez-vous une forte préférence pour préserver votre intégrité emotionel dans vos actions quotidiennes ?"},
    {type: "Fi", question: "Trouvez-vous que vous ressentez intensément vos émotions, mais que vous les gardez souvent pour vous-même ?"},
    {type: "Fi", question: "Vous arrive-t-il de prendre vos distances face à des situations qui contredisent vos valeurs personnelles ?"},
]


