let questions = [
    {type: "Si", question: `Est-ce qu'un objet anodin (un vieux stylo, une tasse fissurée) peut facilement raviver en vous un souvenir précis et chargé d'émotion ?`},
    {type: "Si", question: `Lorsque vous pensez à une personne, est-ce que les petits détails qui vous sont propres (son expression favorite, le son de son rire) vous viennent immédiatement à l'esprit ?`},
    {type: "Si", question: `Est-ce que vous accordez une grande importance aux rituels et aux habitudes familières, car ils ancrent votre quotidien dans un cadre rassurant ?`},
    {type: "Si", question: `Pour vous, la valeur d'un lieu est-elle souvent liée aux souvenirs personnels et aux expériences intimes que vous y avez vécues ?`},
    {type: "Si", question: `Lorsque vous devez prendre une décision, est-ce que vous vous appuyez souvent sur un sentiment de familiarité (ce que vous connaissez déjà) ?`},
    {type: "Si", question: `Est-ce que vous avez une mémoire très précise des anecdotes, des dates anniversaires et des événements personnels qui ont marqué votre entourage ?`},
    {type: "Si", question: `Trouvez-vous qu'un endroit devient "votre" endroit une fois que vous l'avez imprégné de vos propres habitudes et expériences répétées ?`},
    {type: "Si", question: `Est-ce que les objets que vous possédez ont souvent une "histoire" ou une signification personnelle qui dépasse leur fonction utilitaire ?`},
    {type: "Si", question: `Avez-vous le sentiment que votre identité est tissée à partir de ce patrimoine de détails familiers et de souvenirs partagés ?`},
    {type: "Si", question: `Est-ce que vous remarquez les petits changements dans les habitudes des personnes qui vous sont chères ?`},

    {type: "Se", question: `Est-ce que votre attention se capture automatiquement sur le détail anormal ou incohérent dans un paysage qui semble ordinaire ?`},
    {type: "Se", question: `Lorsque vous devez agir, est-ce que vous effectuez d'abord un rapide scan de votre environnement pour repérer les objets ou éléments immédiatement utilisables ?`},
    {type: "Se", question: `Est-ce que vous évaluez instinctivement les distances, les trajectoires et les positions relatives des choses et des gens autour de vous ?`},
    {type: "Se", question: `Est-ce que vous modifiez votre posture ou votre itinéraire en temps réel en fonction du mouvement des objets ou des personnes dans votre espace immédiat ?`},
    {type: "Se", question: `Lors d'une interaction, est-ce que vous notez continuellement les micro-changements dans l'environnement (une lumière qui s'éteint, une porte qui s'ouvre) sans perdre le fil ?`},
    {type: "Se", question: `Trouvez-vous que votre esprit fonctionne comme un système de surveillance, constamment à l'affût des variations dans le champ visuel ou sonore proche ?`},
    {type: "Se", question: `Est-ce que vous avez tendance à interagir physiquement avec votre environnement (toucher, déplacer, tester) pour en comprendre les propriétés actuelles ?`},
    {type: "Se", question: `Avez-vous l'impression que la situation présente offre toujours suffisamment d'informations concrètes pour décider de la prochaine action à entreprendre ?`},
    {type: "Se", question: `En entrant dans un lieu, est-ce que les couleurs, les formes et les textures des objets vous frappent immédiatement, avant même de réfléchir à leur utilité ?`},
    {type: "Se", question: `Quand vous écoutez une conversation, est-ce que vous remarquez d'abord la hauteur de la voix ou son timbre, avant même de vous concentrer sur le sens des mots ?`},

    {type: "Ne", question: `Est-ce que votre esprit fonctionne naturellement par associations d'idées, une pensée en amenant une autre de manière parfois imprévisible ?`},
    {type: "Ne", question: `Lorsque vous apprenez un nouveau concept, est-ce que vous passez immédiatement en revue tout ce que vous savez déjà pour trouver des points de connexion ?`},
    {type: "Ne", question: `est ce que vous aimez imaginer des scénarios ou possibilités alternatives, même à partir de petits détails du quotidien.`},
    {type: "Ne", question: `est ce que vos associations d’idées ne suivent pas toujours une logique linéaire, mais se développent dans plusieurs directions.`},
    {type: "Ne", question: `Est-ce qu'une simple sensation (une odeur, une texture, une image) peut instantanément déclencher dans votre esprit une idée lié ?`},
    {type: "Ne", question: `Lors d'une conversation, est-ce que vous sautez facilement d'un sujet à l'autre parce que vous percevez le lien qui les unit, même si ce n'est pas évident pour les autres ?`},
    {type: "Ne", question: `Est-ce que vos pensées avancent souvent "par ricochet", une idée en faisant jaillir une autre de manière imprévisible et créative ?`},
    {type: "Ne", question: `Trouvez-vous que la beauté d'une idée réside souvent dans son élégance et sa capacité à relier harmonieusement plusieurs concepts ?`},
    {type: "Ne", question: `Est-ce qu'un détail anodin peut déclencher en vous une cascade de réflexions qui vous mènent à un concept très éloigné du point de départ ?`},
    {type: "Ne", question: `Avez-vous le sentiment que la connaissance n'est pas une collection de faits, mais une toile infinie de connexions à explorer ?`},

    {type: "Ni", question: `Lorsque vous avez une intuition très forte sur quelque chose, avez-vous tendance à lui faire confiance même si vous manquez de preuves concrètes pour l'étayer ?`},
    {type: "Ni", question: `Est-ce que vous arrivez souvent à "voir" la solution d'un problème dans votre tête avant de pouvoir l'expliquer logiquement à quelqu'un ?`},
    {type: "Ni", question: `Si les données statistiques vont à l'encontre de votre instinct, remettez-vous plus souvent les données en question que votre instinct ?`},
    {type: "Ni", question: `Pour vous, est-ce que "comprendre" un concept, c'est surtout réussir à en former une image ou une vision claire dans votre esprit ?`},
    {type: "Ni", question: `Préférez-vous avoir une vue d'ensemble approximative mais cohérente d'un sujet plutôt qu'une liste détaillée de faits sans liens évidents ?`},
    {type: "Ni", question: `Une idée qui vous semble "vraie dans son essence" est-elle pour vous plus convaincante qu'une idée simplement logique ?`},
    {type: "Ni", question: `Est-ce qu'une métaphore ou une analogie puissante vous persuade souvent plus qu'une longue liste d'arguments ?`},
    {type: "Ni", question: `Votre processus de réflexion ressemble-t-il plus à une lente maturation d'idées qui finissent par "cliquer" qu'à une analyse séquentielle ?`},
    {type: "Ni", question: `Pour prédire l'issue d'une situation, vous fiez-vous davantage à vos pressentiments qu'à une analyse des tendances passées ?`},
    {type: "Ni", question: `Face à un ensemble de données brutes, votre premier réflexe est-il de chercher le "pourquoi" et la "signification" derrière ces chiffres ?`},
    
    {type: 'Te', question: `Est-ce que vous avez naturellement tendance à traduire des observations qualitatives (comme une ambiance) en données ou en pourcentages ?`},
    {type: 'Te', question: `Lorsqu'on vous présente une idée, est-ce que vous cherchez immédiatement les indicateurs ou les métriques qui pourraient en mesurer la performance ?`},
    {type: 'Te', question: `Est-ce que vous faites davantage confiance à un graphique ou à un tableau de chiffres qu'à un long discours descriptif pour vous faire une opinion ?`},
    {type: 'Te', question: `Pour prendre une décision personnelle, est-ce que vous créez parfois des tableaux coûts/bénéfices ou des systèmes de notation pour comparer les options ?`},
    {type: 'Te', question: `Est-ce que le monde vous semble plus clair et plus prévisible lorsque vous pouvez le modéliser avec des données et des statistiques ?`},
    {type: 'Te', question: `Lorsque vous parlez d'un sujet qui vous passionne, est-ce que vous citez souvent des chiffres, des études ou des résultats concrets pour étayer vos propos ?`},
    {type: 'Te', question: `Est-ce que vous aimez les outils (comme les applications de suivi) qui vous permettent de mesurer et d'analyser vos propres performances ou habitudes ?`},
    {type: 'Te', question: `Trouvez-vous satisfaisant de pouvoir représenter une réalité complexe sous la forme d'un chiffre clair ou d'une valeur unique (un KPI) ?`},
    {type: 'Te', question: `Est-ce que vous êtes sceptique face aux affirmations qui ne s'appuient sur aucun chiffre ou donnée vérifiable ?`},
    {type: 'Te', question: `Est-ce que vous percevez la beauté ou l'élégance dans la manière dont des données s'organisent pour révéler une tendance ou un résultat ?`},

    {type: 'Ti', question: `Même si une conclusion vous semble globalement correcte, avez-vous besoin de vérifier la logique de chaque étape du raisonnement pour l'accepter pleinement ?`},
    {type: 'Ti', question: `Pour être convaincu par une théorie, avez-vous besoin de pouvoir la "reconstruire" mentalement, en comprenant comment chaque pièce s'emboîte parfaitement ?`},
    {type: 'Ti', question: `Est-ce que vous estimez ne vraiment comprendre un mécanisme que si vous pouvez l'expliquer de A à Z, sans faille dans le raisonnement ?`},
    {type: 'Ti', question: `Êtes-vous plus facilement frustré par un argument qui contient une contradiction interne que par un argument qui manque simplement de perspective ?`},
    {type: 'Ti', question: `Accordez-vous naturellement plus de poids aux preuves tangibles et aux données d'un mécanisme qu'à une intuition, même si celle-ci est très forte ?`},
    {type: 'Ti', question: `Avant d'adopter une opinion, aimez-vous "démonter" les arguments pour tester la solidité de chaque connexion logique ?`},
    {type: 'Ti', question: `Préférez-vous un modèle mental complexe mais parfaitement cohérent à une vision simple qui comporte des approximations ?`},
    {type: 'Ti', question: `La preuve ultime qu'une idée est bonne est-elle, pour vous, qu'elle fonctionne en pratique selon des principes logiques prévisibles ?`},
    {type: 'Ti', question: `Faites-vous davantage confiance à un processus dont vous comprenez tous les rouages qu'à l'avis d'un expert que vous ne pouvez pas vérifier par vous-même ?`},
    {type: 'Ti', question: `Votre esprit fonctionne-t-il comme un détecteur de incohérences, repérant automatiquement les "bugs" dans les raisonnements que vous entendez ?`},

    {type: 'Fe', question: `Est-ce que vous évaluez souvent la qualité de votre journée en fonction de la nature de vos interactions avec les autres ?`},
    {type: 'Fe', question: `Lorsque vous entrez dans une pièce, est-ce que vous scannez naturellement l'ambiance et les dynamiques émotionnelles entre les personnes présentes ?`},
    {type: 'Fe', question: `Est-ce qu'un désaccord vous semble surtout être une rupture dans la connexion émotionnelle qu'il faut réparer ?`},
    {type: 'Fe', question: `Pour prendre une décision importante, est-ce que votre critère principal est l'impact qu'elle aura sur vos relations proches ?`},
    {type: 'Fe', question: `Est-ce que vous avez l'impression de "ressentir" littéralement les émotions des personnes qui vous entourent, comme si elles étaient contagieuses ?`},
    {type: 'Fe', question: `Lors d'une conversation, êtes-vous plus attentif à ce que la personne ressent qu'à ce qu'elle dit littéralement ?`},
    {type: 'Fe', question: `Est-ce que vous passez beaucoup de temps à analyser et à comprendre les tenants et aboutissants de vos relations ?`},
    {type: 'Fe', question: `Trouvez-vous que le fait d'être en harmonie avec votre entourage est un besoin aussi fondamental que de manger ou de dormir ?`},
    {type: 'Fe', question: `Est-ce que vous avez tendance à prendre personnellement les tensions ou les mauvaises ambiances, même lorsqu'elles ne vous concernent pas directement ?`},
    {type: 'Fe', question: `Avez-vous le sentiment que le sens de la vie se trouve principalement dans la richesse et l'authenticité des liens que l'on tisse avec les autres ?`},

    {type: 'Fi', question: `Face à une situation, est-ce que vous vous demandez spontanément "Est-ce que c'est juste ?" avant de vous demander "Est-ce que c'est efficace ?"`},
    {type: 'Fi', question: `Lorsque vous entendez un discours ou un argument, est-ce que vous évaluez d'abord sa cohérence avec vos valeurs morales fondamentales ?`},
    {type: 'Fi', question: `Est-ce que vos décisions importantes sont principalement guidées par un besoin profond d'agir en accord avec vos principes éthiques ?`},
    {type: 'Fi', question: `Est-ce que vous passez du temps à réfléchir et à affiner votre propre "boussole morale" pour qu'elle soit la plus juste possible ?`},
    {type: 'Fi', question: `Lorsque vos valeurs entrent en conflit avec une règle établie, est-ce que vous ressentez une forte tension intérieure ?`},
    {type: 'Fi', question: `Est-ce que vous êtes particulièrement sensible aux questions de justice, d'équité et d'intégrité, que ce soit dans la vie quotidienne ou à grande échelle ?`},
    {type: 'Fi', question: `Trouvez-vous que les actions des gens n'ont de sens profond que si elles sont alignées avec un système de valeurs cohérent ?`},
    {type: 'Fi', question: `Est-ce que vous avez besoin de comprendre les motivations et les valeurs qui animent une personne pour vraiment pouvoir lui faire confiance ?`},
    {type: 'Fi', question: `Lorsque vous lisez une histoire ou regardez un film, est-ce que vous êtes naturellement attiré par les dilemmes moraux et les conflits de valeurs des personnages ?`},
    {type: 'Fi', question: `Avez-vous le sentiment que votre identité est largement définie par les valeurs auxquelles vous choisissez de rester fidèle, même dans l'adversité ?`},
]

