let questions = [
    {type: "Si", org: false, question: `Possédez-vous une mémoire fidèle et détaillée des expériences personnelles passées ?`},
    {type: "Si", org: false, question: `Accordez-vous une grande importance au maintien de routines, d'habitudes et d'un environnement stable, car cela procure un sentiment de confort, de sécurité et de maîtrise prévisible sur votre quotidien ?`},
    {type: "Si", org: false, question: `Votre force réside-t-elle dans votre capacité à évaluer des éléments présent avec une précision et une fiabilité méticuleuses, en vous appuyant sur des procédures et des connaissances approfondie des détails concrets ?`},
    {type: "Si", org: true, question: `Votre attachement aux façons de faire éprouvées et familières vous rend-il réfractaire au changement et à l'innovation, même lorsque ceux-ci sont nécessaires ou bénéfiques, par peur de l'inconnu ou de perdre ce repère stable ?`},
    {type: "Si", org: true, question: `Votre focalisation sur les détails familiers et les comparaisons avec le passé vous fait-elle parfois manquer la vision d'ensemble, le sens ou le potentiel futur d'une situation, vous enfermant dans une perspective étroite ?`},
    {type: "Si", org: true, question: `Votre besoin de comparer chaque nouvelle situation à votre catalogue interne d'expériences vous entraîne-t-il dans des analyses paralysantes ou des décisions retardées, par crainte de ne pas avoir assez de points de référence pour agir en toute sécurité ?`},

    {type: "Se", org: false, question: `Êtes-vous particulièrement doué(e) pour réagir avec rapidité et efficacité aux opportunités ou aux dangers qui se présentent dans l'environnement immédiat, sans avoir besoin de longues réflexions ?`},
    {type: "Se", org: false, question: `Eprouvez vous un plaisir intense et une forme de présence totale lors d'expériences sensorielles fortes (sports, arts, nature, sensations physiques) qui vous ancrent pleinement dans l'instant présent ?`},
    {type: "Se", org: false, question: `Votre capacité à percevoir et à manipuler les détails concrets de votre environnement (objets, espaces, apparences) est-elle souvent remarquée par les autres comme un talent pratique et efficace ?`},
    {type: "Se", org: true, question: `Votre impulsivité et votre recherche de sensations fortes vous ont-elles déjà conduit à prendre des risques physiques ou financiers inconsidérés, simplement pour vaincre l'ennui ou ressentir l'excitation de l'instant ?`},
    {type: "Se", org: true, question: `Avez-vous du mal à vous engager dans des projets ou des relations qui exigent de la patience et de la persévérance sur le long terme, préférant l'immédiateté et le changement constant ?`},
    {type: "Se", org: true, question: `Votre focalisation sur l'action et le résultat immédiat vous rend-elle parfois aveugle aux implications plus larges, stratégiques ou émotionnelles de vos actes, causant des problèmes que vous n'aviez pas anticipés ?`},

    {type: "Ne", org: false, question: `Votre esprit a-t-il tendance à générer naturellement et spontanément de multiples idées, associations ou interprétations possibles à partir d'un seul point de départ, sans effort conscient ?`},
    {type: "Ne", org: false, question: `Trouvez-vous plus stimulant et satisfaisant d'explorer le champ des possibles et des idées neuves que de vous concentrer sur la mise en œuvre pratique d'un seul plan déjà établi ?`},
    {type: "Ne", org: false, question: `Êtes-vous souvent celui/celle qui, dans une discussion, fait des liens inattendus entre des domaines apparemment éloignés, ouvrant ainsi des perspectives nouvelles que les autres n'avaient pas envisagées ?`},
    {type: "Ne", org: true, question: `Votre facilité à voir des possibilités partout vous conduit elle souvent à démultiplier les projets tout en ayant du mal à en mener un seul à son terme, créant une pile de 'brillantes idées inachevées' ?`},
    {type: "Ne", org: true, question: `Votre enthousiasme pour les nouvelles idées et connections vous rend-il insensible ou impatient face aux personnes qui ont besoin de stabilité, de détails pratiques ou de suivre des procédures établies, que vous jugez 'limitées' ?`},
    {type: "Ne", org: true, question: `Votre besoin constant de nouveauté et de stimulation intellectuelle vous empêche-t-il de vous engager en profondeur, que ce soit dans une spécialisation, un projet à long terme ou même une relation, par peur de vous 'enfermer' et de manquer d'autres possibilités ?`},

    {type: "Ni", org: false, question: `Lorsque vous comprenez vraiment un sujet complexe, est-ce sous la forme d'une image globale ou d'un principe unique qui rend soudainement tous les détails superflus ?`},
    {type: "Ni", org: false, question: `Vos intuitions ou prévisions les plus justes se sont-elles souvent imposées à vous comme des certitudes soudaines, bien avant que vous ne puissiez en expliquer les raisons ?`},
    {type: "Ni", org: false, question: `Avez-vous l'impression de percevoir les schémas répétitifs et intemporels (les "archétypes") qui se cachent derrière les événements apparemment uniques, des relations ou de l'histoire ?`},
    {type: "Ni", org: true, question: `Votre confiance dans vos visions intérieures vous a-t-elle déjà rendu sourd aux faits concrets et aux retours d'expérience qui les contredisaient, vous conduisant à persister dans l'erreur par fidélité à votre schéma ?`},
    {type: "Ni", org: true, question: `Les autres vous reprochent ils régulièrement de vivre "dans votre monde", déconnecté des réalités pratiques et des détails évidents pour tous, au point que cela nuit à certains aspect de votre vie ?`},
    {type: "Ni", org: true, question: `Eprouvez vous une frustration profonde et récurrente lorsque vous devez expliquer le cheminement de votre pensée, car vous ne pouvez que montrer la conclusion (évidente pour vous), mais jamais reconstituer les étapes ?`},
    
    {type: 'Te', org: false, question: `Face à un problème, votre premier réflexe est-il de chercher à identifier le levier causal principal sur lequel agir pour obtenir un résultat mesurable et prévisible ?`},
    {type: 'Te', org: false, question: `Eprouvez vous une profonde satisfaction à structurer les processus (travail, projets, informations) en étapes claires et logiques, pour les rendre plus efficaces et reproductibles ?`},
    {type: 'Te', org: false, question: `Considérez-vous qu'un argument ou une décision n'est vraiment solide que si elle s'appuie sur des données vérifiables, des preuves concrètes ou un raisonnement causal démontrable ?`},
    {type: 'Te', org: true, question: `Votre recherche d'efficacité et de logique vous a-t-elle déjà conduit à écarter ou blesser des personnes dont les contributions ou les sentiments vous paraissaient 'irrationnels' ou 'contre-productifs' par rapport à l'objectif ?`},
    {type: 'Te', org: true, question: `Avez-vous tendance à dévaloriser ou ignorer les idées, intuitions ou valeurs qui ne peuvent pas être immédiatement traduites en actions concrètes ou en résultats mesurables, les jugeant 'inutiles' ?`},
    {type: 'Te', org: true, question: `Votre confiance dans les modèles causaux vous rend-elle aveugle aux phénomènes complexes (comme les dynamiques humaines, culturelles ou systémiques) qui résistent à une analyse simple de cause à effet, vous conduisant parfois à des erreurs de jugement flagrantes ?`},

    {type: 'Ti', org: false, question: `Lorsque vous abordez un nouveau sujet, éprouvez vous un besoin presque esthétique d'en comprendre la structure logique interne avant de pouvoir l'utiliser ou en parler ?`},
    {type: 'Ti', org: false, question: `Trouvez-vous plus satisfaisant de résoudre un problème en découvrant le principe organisateur qui l'explique entièrement, plutôt que d'empiler des solutions pratiques mais disjointes ?`},
    {type: 'Ti', org: false, question: `Avant d'adopter une opinion ou une explication, éprouves tu le besoin de la démonter mentalement pour vérifier la solidité et la cohérence de chaque partie du raisonnement ?`},
    {type: 'Ti', org: true, question: `Votre attachement à la cohérence interne parfaite de vos raisonnements vous a-t-il déjà conduit à ignorer des preuves empiriques ou des résultats concrets, simplement parce qu'ils 'ne s'emboîtaient pas bien' dans votre modèle ?`},
    {type: 'Ti', org: true, question: `Lorsque quelqu'un utilise un terme de manière imprécise ou métaphorique dans une discussion sérieuse, éprouvez vous un mépris immédiat pour son argument, même si son intuition de fond pourrait être valable ?`},
    {type: 'Ti', org: true, question: `Avez-vous déjà passé plus de temps à raffiner mentalement votre compréhension d'un système qu'à agir concrètement dans ce domaine, au point que votre perfectionnisme cognitif est devenu une forme de procrastination ?`},

    {type: 'Fe', org: false, question: `Êtes-vous naturellement capable de sentir et lire l'atmosphère émotionnelle d'une pièce ou d'un groupe dès que vous y entrez, et de vous y adapter ?`},
    {type: 'Fe', org: false, question: `Considérez-vous qu'il est souvent nécessaire et juste de modérer vos propres opinions ou besoins personnels pour préserver l'harmonie et la cohésion d'un groupe qui vous est cher ?`},
    {type: 'Fe', org: false, question: `Lorsque vous prenez une décision importante, le critère de son impact sur le bien-être et la dynamique du groupe pèse-t-il aussi lourd, sinon plus, que son efficacité logique ou son mérite personnel ?`},
    {type: 'Fe', org: true, question: `Votre désir d'harmonie vous a-t-il déjà conduit à étouffer une vérité importante ou à laisser passer une injustice par peur de créer un conflit ou de perturber le groupe ?`},
    {type: 'Fe', org: true, question: `Avez-vous parfois le sentiment de ne pas savoir qui vous êtes vraiment en dehors des attentes et des rôles que vous jouez pour répondre aux besoins émotionnels des différents groupes que vous fréquentez ?`},
    {type: 'Fe', org: true, question: `Utilisez-vous consciemment votre compréhension des émotions des autres pour influencer ou manipuler doucement les décisions collectives dans le sens que vous estimez le meilleur pour le groupe (ou pour vous) ?`},

    {type: 'Fi', org: false, question: `Prenez-vous des décisions importantes (choix de vie, relations) principalement en fonction d'un sentiment profond d'alignement ou de dissonance interne, même si cela va à l'encontre de la logique, des conventions ou des attentes extérieures ?`},
    {type: 'Fi', org: false, question: `La sensation de 'fausseté' ou d'inauthenticité (en vous-même ou perçue chez les autres) vous cause-t-elle un inconfort profond, parfois physique, qui agit comme un signal d'alarme puissant ?`},
    {type: 'Fi', org: false, question: `Vos valeurs personnelles forment-elles un système interne cohérent et hiérarchisé, une 'constitution' personnelle qui vous sert de référence ultime pour évaluer les expériences et les personnes ?`},
    {type: 'Fi', org: true, question: `Votre attachement à votre authenticité vous a-t-il déjà conduit à juger sévèrement ou rejeter des personnes que vous perceviez comme 'fausses' ou 'superficielles', sans chercher à comprendre les raisons ou contraintes qui les ont façonnées ?`},
    {type: 'Fi', org: true, question: `Avez-vous tendance à interpréter les désaccords ou les critiques comme des attaques contre vos valeurs fondamentales, rendant les compromis impossibles et les débats rationnels, personnels et douloureux ?`},
    {type: 'Fi', org: true, question: `Votre focalisation vos valeurs vous isole-t-elle parfois, créant un fossé de solitude où vous vous sentez fondamentalement incompris, tout en faisant peu d'efforts pour traduire et partager ces valeurs avec les autres ?`},
]

/*
{type: "Te", question: "Vous sentez-vous motivé à organiser les choses pour qu'elles soient plus efficaces et productives ?"},
    {type: "Te", question: "Aimez-vous prendre des décisions rapidement en vous basant sur des faits objectifs ?"},
    {type: "Te", question: "Vous trouvez-vous souvent à vouloir structurer et planifier les étapes nécessaires pour atteindre un objectif ?"},
    {type: "Te", question: "Aimez-vous donner des instructions ou conseils pour aider les autres à être plus efficaces ?"},
    {type: "Te", question: "Trouvez-vous que vous prenez facilement les commandes dans les situations qui nécessitent une organisation ?"},
    {type: "Te", question: "Appréciez-vous fixer des objectifs clairs et mesurer vos progrès de manière tangible ?"},
    {type: "Te", question: "Aimez-vous résoudre les problèmes en vous basant sur des données factuelles et objectives ?"},
    {type: "Ti", question: "Avez-vous une tendance à analyser les situations en profondeur pour en comprendre les mécanismes sous-jacents ?"},
    {type: "Ti", question: "Vous appuyez-vous sur des principes logiques internes pour prendre des décisions, même si elles ne sont pas populaires ?"},
    {type: "Ti", question: "Avez-vous un fort besoin de cohérence et de clarté dans vos idées et croyances ?"},
    {type: "Ti", question: "Aimez-vous décomposer des problèmes complexes en éléments plus simples et compréhensibles ?"},
    {type: "Ti", question: "Ressentez-vous une satisfaction personnelle lorsque vous trouvez des solutions logiques et bien raisonnées ?"},
    {type: "Ti", question: "Vous sentez-vous souvent concentré sur le \"pourquoi\" des choses, en cherchant à comprendre leur fonctionnement ?"},
    {type: "Ti", question: "Avez-vous une forte préférence pour des décisions qui s'accordent avec vos propres modèles de pensée logique ?"},
    {type: "Fe", question: "Aimez-vous vous assurer que les autres se sentent bien et sont émotionnellement à l'aise ?"},
    {type: "Fe", question: "Trouvez-vous important de maintenir l'harmonie et d'éviter les conflits au sein de votre entourage ?"},
    {type: "Fe", question: "Vous retrouvez-vous souvent à prendre des décisions basées sur les besoins et les désirs des autres ?"},
    {type: "Fe", question: "Avez-vous tendance à exprimer ouvertement vos émotions et à vous soucier des réactions des autres ?"},
    {type: "Fe", question: "Vous arrive-t-il souvent d'agir pour soutenir ou aider les autres dans leurs difficultés ?"},
    {type: "Fe", question: "Aimez-vous construire des relations chaleureuses et sincères ?"},
    {type: "Fe", question: "Prenez-vous du plaisir à rassemblé les gens et favorisé l'harmonie ?"},
    {type: "Fi", question: "Prenez-vous souvent des décisions en fonction de vos valeurs personnelles profondes ?"},
    {type: "Fi", question: "Vous arrive-t-il de ressentir fortement ce qui est juste ou injuste en fonction de vos propres standards ?"},
    {type: "Fi", question: "Trouvez-vous important de rester fidèle à vous-même, même si cela entre en conflit avec l'avis des autres ?"},
    {type: "Fi", question: "Vous appuyez-vous souvent sur vos convictions personnelles pour évaluer une situation ?"},
    {type: "Fi", question: "Avez-vous une forte préférence pour préserver votre intégrité emotionel dans vos actions quotidiennes ?"},
    {type: "Fi", question: "Trouvez-vous que vous ressentez intensément vos émotions, mais que vous les gardez souvent pour vous-même ?"},
    {type: "Fi", question: "Vous arrive-t-il de prendre vos distances face à des situations qui contredisent vos valeurs personnelles ?"},
*/

/*
{type: "Se", question: "Vous trouvez-vous souvent en quête d'expériences stimulantes et nouvelles ?"},
    {type: "Se", question: "Prenez-vous plaisir à être impliqué dans des activités physiques qui sollicitent vos sens ?"},
    {type: "Se", question: "Êtes-vous souvent attiré par ce qui se passe ici et maintenant ?"},
    {type: "Se", question: "Avez-vous tendance à agir rapidement en fonction de ce que vous voyez, entendez ou ressentez autour de vous ?"},
    {type: "Se", question: "Lorsque vous interagissez avec votre environnement, ressentez-vous un fort besoin de toucher et d'explorer directement ?"},
    {type: "Se", question: "Est-ce que les détails et les aspects concrets de votre environnement captent immédiatement votre attention ?"},
    {type: "Se", question: "Vous vous sentez plus vivant lorsque vous êtes activement engagé dans le monde extérieur ?"},
    {type: "Si", question: "Trouvez-vous que vous préférez faire confiance à des méthodes éprouvées basées sur vos expériences passées ?"},
    {type: "Si", question: "Aimez-vous vous remémorer des souvenirs en détail et ressentir les émotions qu'ils évoquent ?"},
    {type: "Si", question: "Vous appuyez-vous souvent sur des routines bien établies pour guider vos actions ?"},
    {type: "Si", question: "Préférez-vous vous référer à ce que vous connaissez déjà avant d'essayer quelque chose de nouveau ?"},
    {type: "Si", question: "Avez-vous un fort sens de ce qui est correct ou approprié dans une situation en fonction de ce que vous avez appris auparavant ?"},
    {type: "Si", question: "Vous sentez-vous à l'aise lorsque vous pouvez vous appuyer sur vos souvenirs pour naviguer dans de nouvelles situations ?"},
    {type: "Si", question: "Tenez-vous à préserver vos habitudes ?"},
    {type: "Ne", question: "Vous arrive-t-il de voir immédiatement plusieurs possibilités ou alternatives dans une situation donnée ?"},
    {type: "Ne", question: "Aimez-vous brainstormer ou générer des idées nouvelles et originales ?"},
    {type: "Ne", question: "Vous retrouvez-vous souvent en train de relier des idées apparemment non liées ?"},
    {type: "Ne", question: "Vous sentez-vous stimulé par la découverte de nouvelles idées et concepts qui vous mènent à des solutions créatives ?"},
    {type: "Ne", question: "Trouvez-vous que votre esprit saute souvent d'une idée à une autre, connectant des points de manière imaginative ?"},
    {type: "Ne", question: "Aimez-vous explorer les potentialités plutôt que de vous limiter à ce qui est évident ou concret ?"},
    {type: "Ne", question: "Prenez-vous du plaisir à envisager différentes perspectives et scénarios simultanément ?"},
    {type: "Ni", question: "Vous arrive-t-il souvent d'avoir une vision claire de la direction que vous souhaitez prendre à long terme ?"},
    {type: "Ni", question: "Avez-vous l'impression de comprendre intuitivement le sens profond des événements ou situations ?"},
    {type: "Ni", question: "Vous trouvez-vous attiré par des concepts ou des idées abstraites que vous voulez approfondir ?"},
    {type: "Ni", question: "Ressentez-vous une forte confiance dans vos intuitions internes, même si elles ne sont pas toujours explicables ?"},
    {type: "Ni", question: "Prenez-vous plaisir à élaborer des théories complexes et des schémas mentaux ?"},
    {type: "Ni", question: "Vous arrive-t-il souvent de chercher à comprendre les motivations profondes des autres ou des événements ?"},
    {type: "Ni", question: "Pensez-vous souvent à l'avenir et aux possibilités que vous pourriez explorer ?"},
*/

/*let questions = [
    {type: "Si", question: "Est-ce que tu préfères suivre des méthodes éprouvées plutôt que d’inventer de nouvelles façons de faire ?"},
    {type: "Si", question: "Accordes-tu plus d’importance aux détails concrets (ex: horaires, budget) qu’à la vision globale d’un projet ?"},
    {type: "Si", question: "Te souviens-tu facilement de détails spécifiques (odeurs, sons, images) d’événements passés ?"},
    {type: "Si", question: "Les traditions ou habitudes établies te rassurent-elles ?"},
    {type: "Si", question: "Préfères-tu apprendre via des exemples concrets plutôt que des théories abstraites ?"},
    {type: "Si", question: "Recherches-tu la stabilité et la prévisibilité dans tes projets ?"},
    {type: "Si", question: "Te bases-tu sur tes propres expériences passées pour prendre des décisions ?"},
    {type: "Si", question: "Planifies-tu méticuleusement (ex: listes, étapes précises) avant d’agir ?"},
    {type: "Si", question: "Le confort matériel (ex: lieu de vie, nourriture) est-il essentiel pour toi ?"},
    {type: "Si", question: "Suis-tu naturellement les règles ou procédures existantes sans les remettre en question ?"},
    {type: "Si", question: "Compares-tu souvent les situations actuelles à des situations similaires vécues ?"},
    {type: "Si", question: "Les erreurs de détails (ex: fautes d’orthographe, chiffres inexacts) te dérangent-elles beaucoup ?"},
    {type: "Si", question: "Portes-tu une attention particulière à tes sensations physiques (fatigue, faim, douleur) ?"},
    {type: "Si", question: "Attaches-tu de l’importance aux objets souvenirs ou aux héritages familiaux ?"},
    {type: "Si", question: "Tes routines quotidiennes sont-elles difficiles à changer ?"},
    {type: "Si", question: "Préfères-tu les solutions pratiques et immédiates aux idées innovantes mais incertaines ?"},
    {type: "Si", question: "Te sens-tu plus à l’aise en parlant de faits tangibles que de concepts hypothétiques ?"},
    {type: "Si", question: "Anticiper les problèmes concrets (ex: prévoir un parapluie) est-il naturel pour toi ?"},
    {type: "Si", question: "Revivre des moments passés (photos, lieux familiers) te procure-t-il du réconfort ?"},
    {type: "Si", question: "Utilises-tu des systèmes éprouvés (ex: checklists, modèles) pour rester efficace ?"},
    {type: "Ni", question: "Penses-tu souvent à ton avenir lointain (5-10 ans) avec une image claire ?"},
    {type: "Ni", question: "Fusionnes-tu des idées complexes en un seul concept ou symbole ?"},
    {type: "Ni", question: "As-tu souvent des intuitions soudaines qui se réalisent ?"},
    {type: "Ni", question: "Préfères-tu discuter de théories ou de possibilités futures plutôt que de faits bruts ?"},
    {type: "Ni", question: "Cherches-tu un sens profond derrière les événements ou les paroles ?"},
    {type: "Ni", question: "Te projettes-tu naturellement dans des scénarios futurs (positifs ou négatifs) ?"},
    {type: "Ni", question: "Les détails pratiques te semblent-ils secondaires par rapport à l'objectif final ?"},
    {type: "Ni", question: "Utilises-tu des analogies ou des symboles pour expliquer tes idées ?"},
    {type: "Ni", question: "Tes meilleures idées viennent-elles par \"flash\" sans effort conscient ?"},
    {type: "Ni", question: "Es-tu à l'aise pour réinventer tes méthodes si tu vois une meilleure voie ?"},
    {type: "Ni", question: "Remarques-tu des liens entre des domaines apparemment sans rapport ?"},
    {type: "Ni", question: "Les mystères (ex: énigmes philosophiques) te captivent-ils ?"},
    {type: "Ni", question: "Optes-tu pour des solutions élégantes/innovantes même si elles sont risquées ?"},
    {type: "Ni", question: "Passes-tu du temps perdu dans tes pensées à imaginer des scénarios ?"},
    {type: "Ni", question: "Te vois-tu constamment en transformation vers une version \"idéale\" de toi-même ?"},
    {type: "Ni", question: "Comprends-tu mieux les situations en voyant d'abord la \"big picture\" ?"},
    {type: "Ni", question: "Arrives-tu à des conclusions sans pouvoir expliquer chaque étape logique ?"},
    {type: "Ni", question: "Tes plans initiaux changent-ils si une nouvelle perspective émerge ?"},
    {type: "Ni", question: "Penses-tu en termes de modèles universels (ex: cycles historiques, symboles) ?"},
    {type: "Ni", question: "Tes décisions sont-elles guidées par une \"vision\" ou un pressentiment ?"},
]

let questions = [
    {type: "Ti", question: "Décomposes-tu mentalement les choses pour comprendre comment elles fonctionnent ?"},
    {type: "Ti", question: "Préfères-tu résoudre les problèmes en écartant tes émotions pour rester \"logique\" ?"},
    {type: "Ti", question: "T'intéresses-tu aux modèles, théories ou cadres conceptuels pour expliquer le monde ?"},
    {type: "Ti", question: "Corriges-tu les incohérences ou imprécisions dans les discours des autres ? (même en privé)"},
    {type: "Ti", question: "Passes-tu du temps à explorer des sujets complexes par pur intérêt intellectuel ?"},
    {type: "Ti", question: "Dans un conflit, cherches-tu d'abord à comprendre les faits plutôt qu'à apaiser les sentiments ?"},
    {type: "Ti", question: "Utilises-tu naturellement un vocabulaire technique ou des définitions rigoureuses ?"},
    {type: "Ti", question: "Remets-tu en question les méthodes existantes si elles te semblent \"illogiques\" ?"},
    {type: "Ti", question: "Te sens-tu mal à l'aise quand on attend de toi une prise de position émotionnelle ?"},
    {type: "Ti", question: "Analyses-tu les causes profondes d'un problème plutôt que ses conséquences émotionnelles ?"},
    {type: "Ti", question: "Apprécies-tu les énigmes logiques, les échecs ou les débats d'idées abstraites ?"},
    {type: "Ti", question: "Une idée doit-elle être \"cohérente\" pour toi, même si elle est impopulaire ?"},
    {type: "Ti", question: "Construis-tu des modèles mentaux personnels pour organiser tes connaissances ?"},
    {type: "Ti", question: "Tes propres émotions te gênent-elles quand tu dois prendre une décision importante ?"},
    {type: "Ti", question: "Classifies-tu les informations par catégories logiques pour mieux les comprendre ?"},
    {type: "Ti", question: "Te motives-tu davantage par les problèmes complexes à résoudre que par les relations ?"},
    {type: "Ti", question: "Remets-tu sans cesse tes raisonnements à jour pour les rendre plus efficaces ?"},
    {type: "Ti", question: "Ignores-tu les règles sociales si elles te semblent irrationnelles ?"},
    {type: "Ti", question: "Préfères-tu les explications techniques aux discours inspirants ou poétiques ?"},
    {type: "Ti", question: "Admets-tu facilement tes erreurs de logique quand on te les prouve ?"},

    {type: "Fi", question: "As-tu un code moral interne fort, même différent des normes sociales ?"},
    {type: "Fi", question: "Accordes-tu une importance vitale à être fidèle à toi-même ?"},
    {type: "Fi", question: "Décides-tu en fonction de ce qui \"te semble juste\" plutôt que de ce qui est logique ?"},
    {type: "Fi", question: "Ressens-tu intensément les émotions des autres sans forcément les exprimer ?"},
    {type: "Fi", question: "Tes choix visent-ils à préserver ta paix intérieure ou ton intégrité ?"},
    {type: "Fi", question: "Utilises-tu l'art, l'écriture ou la musique pour exprimer tes émotions profondes ?"},
    {type: "Fi", question: "Te bats-tu pour des principes (justice, compassion) même impopulaires ?"},
    {type: "Fi", question: "Évalues-tu les gens sur leur sincérité et leur cohérence éthique plutôt que sur leur réussite ?"},
    {type: "Fi", question: "Tes sentiments sont-ils un critère majeur dans tes décisions ?"},
    {type: "Fi", question: "Partages-tu tes émotions uniquement avec ceux en qui tu as une confiance absolue ?"},
    {type: "Fi", question: "Une idée ou une œuvre t’\"atteint-elle\" quand elle résonne avec tes expériences intimes ?"},
    {type: "Fi", question: "Cherches-tu à comprendre les motivations profondes des gens avant de les juger ?"},
    {type: "Fi", question: "Refuses-tu des opportunités si elles entravent tes valeurs fondamentales ?"},
    {type: "Fi", question: "Analyzes-tu tes propres émotions avec intensité pour mieux te connaître ?"},
    {type: "Fi", question: "L'impact humain d'une décision est-il plus important que son efficacité ?"},
    {type: "Fi", question: "Supportes-tu mal l’hypocrisie ou les comportements qui trahissent tes principes ?"},
    {type: "Fi", question: "Exprimes-tu tes sentiments par des actes symboliques plutôt que des mots ?"},
    {type: "Fi", question: "Définis-tu ton identité à travers tes valeurs, pas tes compétences ou statut ?"},
    {type: "Fi", question: "Agis-tu discrètement pour aider sans attirer l'attention ?"},
    {type: "Fi", question: "Les injustices te provoquent-elles une colère froide et tenace ?"},
]

let questions = [
    {type: "Se", question: "Vous trouvez-vous souvent en quête d'expériences stimulantes et nouvelles ?"},
    {type: "Se", question: "Prenez-vous plaisir à être impliqué dans des activités physiques qui sollicitent vos sens ?"},
    {type: "Se", question: "Êtes-vous souvent attiré par ce qui se passe ici et maintenant ?"},
    {type: "Se", question: "Avez-vous tendance à agir rapidement en fonction de ce que vous voyez, entendez ou ressentez autour de vous ?"},
    {type: "Se", question: "Lorsque vous interagissez avec votre environnement, ressentez-vous un fort besoin de toucher et d'explorer directement ?"},
    {type: "Se", question: "Est-ce que les détails et les aspects concrets de votre environnement captent immédiatement votre attention ?"},
    {type: "Se", question: "Vous vous sentez plus vivant lorsque vous êtes activement engagé dans le monde extérieur ?"},
    {type: "Si", question: "Trouvez-vous que vous préférez faire confiance à des méthodes éprouvées basées sur vos expériences passées ?"},
    {type: "Si", question: "Aimez-vous vous remémorer des souvenirs en détail et ressentir les émotions qu'ils évoquent ?"},
    {type: "Si", question: "Vous appuyez-vous souvent sur des routines bien établies pour guider vos actions ?"},
    {type: "Si", question: "Préférez-vous vous référer à ce que vous connaissez déjà avant d'essayer quelque chose de nouveau ?"},
    {type: "Si", question: "Avez-vous un fort sens de ce qui est correct ou approprié dans une situation en fonction de ce que vous avez appris auparavant ?"},
    {type: "Si", question: "Vous sentez-vous à l'aise lorsque vous pouvez vous appuyer sur vos souvenirs pour naviguer dans de nouvelles situations ?"},
    {type: "Si", question: "Tenez-vous à préserver vos habitudes ?"},
    {type: "Ne", question: "Vous arrive-t-il de voir immédiatement plusieurs possibilités ou alternatives dans une situation donnée ?"},
    {type: "Ne", question: "Aimez-vous brainstormer ou générer des idées nouvelles et originales ?"},
    {type: "Ne", question: "Vous retrouvez-vous souvent en train de relier des idées apparemment non liées ?"},
    {type: "Ne", question: "Vous sentez-vous stimulé par la découverte de nouvelles idées et concepts qui vous mènent à des solutions créatives ?"},
    {type: "Ne", question: "Trouvez-vous que votre esprit saute souvent d'une idée à une autre, connectant des points de manière imaginative ?"},
    {type: "Ne", question: "Aimez-vous explorer les potentialités plutôt que de vous limiter à ce qui est évident ou concret ?"},
    {type: "Ne", question: "Prenez-vous du plaisir à envisager différentes perspectives et scénarios simultanément ?"},
    {type: "Ni", question: "Vous arrive-t-il souvent d'avoir une vision claire de la direction que vous souhaitez prendre à long terme ?"},
    {type: "Ni", question: "Avez-vous l'impression de comprendre intuitivement le sens profond des événements ou situations ?"},
    {type: "Ni", question: "Vous trouvez-vous attiré par des concepts ou des idées abstraites que vous voulez approfondir ?"},
    {type: "Ni", question: "Ressentez-vous une forte confiance dans vos intuitions internes, même si elles ne sont pas toujours explicables ?"},
    {type: "Ni", question: "Prenez-vous plaisir à élaborer des théories complexes et des schémas mentaux ?"},
    {type: "Ni", question: "Vous arrive-t-il souvent de chercher à comprendre les motivations profondes des autres ou des événements ?"},
    {type: "Ni", question: "Pensez-vous souvent à l'avenir et aux possibilités que vous pourriez explorer ?"},
    {type: "Te", question: "Vous sentez-vous motivé à organiser les choses pour qu'elles soient plus efficaces et productives ?"},
    {type: "Te", question: "Aimez-vous prendre des décisions rapidement en vous basant sur des faits objectifs ?"},
    {type: "Te", question: "Vous trouvez-vous souvent à vouloir structurer et planifier les étapes nécessaires pour atteindre un objectif ?"},
    {type: "Te", question: "Aimez-vous donner des instructions ou conseils pour aider les autres à être plus efficaces ?"},
    {type: "Te", question: "Trouvez-vous que vous prenez facilement les commandes dans les situations qui nécessitent une organisation ?"},
    {type: "Te", question: "Appréciez-vous fixer des objectifs clairs et mesurer vos progrès de manière tangible ?"},
    {type: "Te", question: "Aimez-vous résoudre les problèmes en vous basant sur des données factuelles et objectives ?"},
    {type: "Ti", question: "Avez-vous une tendance à analyser les situations en profondeur pour en comprendre les mécanismes sous-jacents ?"},
    {type: "Ti", question: "Vous appuyez-vous sur des principes logiques internes pour prendre des décisions, même si elles ne sont pas populaires ?"},
    {type: "Ti", question: "Avez-vous un fort besoin de cohérence et de clarté dans vos idées et croyances ?"},
    {type: "Ti", question: "Aimez-vous décomposer des problèmes complexes en éléments plus simples et compréhensibles ?"},
    {type: "Ti", question: "Ressentez-vous une satisfaction personnelle lorsque vous trouvez des solutions logiques et bien raisonnées ?"},
    {type: "Ti", question: "Vous sentez-vous souvent concentré sur le \"pourquoi\" des choses, en cherchant à comprendre leur fonctionnement ?"},
    {type: "Ti", question: "Avez-vous une forte préférence pour des décisions qui s'accordent avec vos propres modèles de pensée logique ?"},
    {type: "Fe", question: "Aimez-vous vous assurer que les autres se sentent bien et sont émotionnellement à l'aise ?"},
    {type: "Fe", question: "Trouvez-vous important de maintenir l'harmonie et d'éviter les conflits au sein de votre entourage ?"},
    {type: "Fe", question: "Vous retrouvez-vous souvent à prendre des décisions basées sur les besoins et les désirs des autres ?"},
    {type: "Fe", question: "Avez-vous tendance à exprimer ouvertement vos émotions et à vous soucier des réactions des autres ?"},
    {type: "Fe", question: "Vous arrive-t-il souvent d'agir pour soutenir ou aider les autres dans leurs difficultés ?"},
    {type: "Fe", question: "Aimez-vous construire des relations chaleureuses et sincères ?"},
    {type: "Fe", question: "Prenez-vous du plaisir à rassemblé les gens et favorisé l'harmonie ?"},
    {type: "Fi", question: "Prenez-vous souvent des décisions en fonction de vos valeurs personnelles profondes ?"},
    {type: "Fi", question: "Vous arrive-t-il de ressentir fortement ce qui est juste ou injuste en fonction de vos propres standards ?"},
    {type: "Fi", question: "Trouvez-vous important de rester fidèle à vous-même, même si cela entre en conflit avec l'avis des autres ?"},
    {type: "Fi", question: "Vous appuyez-vous souvent sur vos convictions personnelles pour évaluer une situation ?"},
    {type: "Fi", question: "Avez-vous une forte préférence pour préserver votre intégrité emotionel dans vos actions quotidiennes ?"},
    {type: "Fi", question: "Trouvez-vous que vous ressentez intensément vos émotions, mais que vous les gardez souvent pour vous-même ?"},
    {type: "Fi", question: "Vous arrive-t-il de prendre vos distances face à des situations qui contredisent vos valeurs personnelles ?"},
]
*/